name: Basic Echo Workflow

on:
  push:
    branches:
      - main
on:
  push:
    paths:
      - 'scrips/**'        # Monitora todos os arquivos dentro do diretório "src" e suas subpastas
jobs:
  echo_message:
    runs-on: ubuntu-latest

    steps:
    - name: Echo a message
      run: echo "Hello, GitHub Actions!"
    - name: Echo a message ls -ltr
      run: echo "ls -ltr"
    - name: Rodando um script
      run: |
        cd 
        pwd
        ls -la
        cd work
        pwd 
        ls -la 
        cd automation
        pwd 
        ls -la
        cd automation
        pwd 
        ls -la 
