name: Basic Echo Workflow

on:
  push:
    branches:
      - main

jobs:
  echo_message:
    runs-on: ubuntu-latest

    steps:
    - name: Echo a message
      run: echo "Hello, GitHub Actions!"
    - name: Echo a message ls -ltr
      run: echo "ls -ltr"
    - name: Rodando um script
      run: |
        ls -ltr /home/runner/work/automation/automation
        pwd 
        chmod +x /home/runner/work/automation/automation/scripts/teste.sh
        ./home/runner/work/automation/automation/scripts/teste.sh
